# Generated by Django 5.1.3 on 2024-11-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("новая", "новая"),
                    ("в работе", "в работе"),
                    ("выполнена", "выполнена"),
                    ("отменена", "отменена"),
                ],
                default="новая",
                max_length=9,
            ),
        ),
    ]
